name: Build Console Calculator

on:
  push:
    paths:
      - '**.cpp'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile with g++
        run: g++ console_calculator.cpp -o calculator.exe -static -static-libgcc -static-libstdc++
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-exe
          path: calculator.exe
